version: v2beta1
name: devspace-quickstart-golang

deployments:
  mysql:
    helm:
      values:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: mypassword
          - name: MYSQL_DATABASE
            value: mydatabase
          image: mariadb:10.5.8
          volumeMounts:
          - containerPath: /var/lib/mysql
            volume:
              name: mysql-data
              subPath: /mysql
        service:
          name: mysql
          ports:
          - port: 3306
        volumes:
        - name: mysql-data
          size: 5Gi

dev:
  mysql-port-fwd:
    imageSelector: mariadb
    ports:
      - port: 3333:3306

pipelines:
  mysql-port-fwd: |
    create_deployments --all
    start_dev mysql-port-fwd
